<?php

/* 2013-09-26 hardcoded JSON for statistics.php : 2 levels of array so same javascript can work on both */

$yearInfo = array();
$yearArray = array();
/***************************************************************
to get the data for this set of statistics, run:
  get_statistics_years.php
in a COMMAND WINDOW, on AWS so numbers are live, like this:

  Thu Jan 30 21:22 [aelliott@ip-10-165-44-177:/var/www/ICON $]  php get_statistics_years.php > /home/aelliott/got_statistics_years.json

download it, open it, paste the results after the comment block.

Then perform the replacements below to create a good JSON file for the static statistics set.

//RETAIN THIS EXAMPLE WHEN PASTING NEW UPDATED STATS
year_issues: 39[{"this_year":"0000","year_pubs":136086,"year_issues":619027);
array_push($yearArray, $yearInfo);

$yearInfo = array("this_year"=>"1649","year_pubs"=>1,"year_issues"=>730);
array_push($yearArray, $yearInfo);

UEStudio replacement, not as regex:
},{
with
);^parray_push($yearArray, $yearInfo);^p$yearInfo = array(

AND
":"
with
"=>"

AND then catch the numeric stuff:
":
with
"=>

***************************************************************/

/* BE SURE TO HIDE THE 0000 YEAR
$yearInfo = array("this_year"=>"0000","year_pubs"=>136122,"year_issues"=>619391);
array_push($yearArray, $yearInfo); // April 2015
$yearInfo = array("this_year"=>"0000","year_pubs"=>131797,"year_issues"=>616596);
array_push($yearArray, $yearInfo); // Jan 2016
*/

$yearInfo = array("this_year"=>"1604","year_pubs"=>2,"year_issues"=>2);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1607","year_pubs"=>1,"year_issues"=>1);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1614","year_pubs"=>1,"year_issues"=>1);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1616","year_pubs"=>1,"year_issues"=>1);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1617","year_pubs"=>1,"year_issues"=>1);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1619","year_pubs"=>2,"year_issues"=>2);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1620","year_pubs"=>4,"year_issues"=>4);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1621","year_pubs"=>3,"year_issues"=>3);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1622","year_pubs"=>13,"year_issues"=>29);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1623","year_pubs"=>8,"year_issues"=>48);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1624","year_pubs"=>3,"year_issues"=>21);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1625","year_pubs"=>1,"year_issues"=>16);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1626","year_pubs"=>1,"year_issues"=>1);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1627","year_pubs"=>3,"year_issues"=>8);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1628","year_pubs"=>4,"year_issues"=>4);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1629","year_pubs"=>1,"year_issues"=>1);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1630","year_pubs"=>1,"year_issues"=>2);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1631","year_pubs"=>1,"year_issues"=>4);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1632","year_pubs"=>2,"year_issues"=>6);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1637","year_pubs"=>2,"year_issues"=>2);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1638","year_pubs"=>2,"year_issues"=>2);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1639","year_pubs"=>4,"year_issues"=>4);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1640","year_pubs"=>3,"year_issues"=>3);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1641","year_pubs"=>39,"year_issues"=>46);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1642","year_pubs"=>30,"year_issues"=>77);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1643","year_pubs"=>32,"year_issues"=>238);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1644","year_pubs"=>34,"year_issues"=>311);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1645","year_pubs"=>28,"year_issues"=>311);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1646","year_pubs"=>21,"year_issues"=>168);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1647","year_pubs"=>22,"year_issues"=>149);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1648","year_pubs"=>43,"year_issues"=>274);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1649","year_pubs"=>27,"year_issues"=>503);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1650","year_pubs"=>14,"year_issues"=>508);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1651","year_pubs"=>12,"year_issues"=>540);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1652","year_pubs"=>16,"year_issues"=>523);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1653","year_pubs"=>11,"year_issues"=>517);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1654","year_pubs"=>10,"year_issues"=>505);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1655","year_pubs"=>8,"year_issues"=>437);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1656","year_pubs"=>3,"year_issues"=>467);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1657","year_pubs"=>3,"year_issues"=>422);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1658","year_pubs"=>2,"year_issues"=>417);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1659","year_pubs"=>7,"year_issues"=>432);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1660","year_pubs"=>18,"year_issues"=>488);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1661","year_pubs"=>5,"year_issues"=>105);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1662","year_pubs"=>2,"year_issues"=>103);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1663","year_pubs"=>6,"year_issues"=>104);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1664","year_pubs"=>3,"year_issues"=>105);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1665","year_pubs"=>7,"year_issues"=>138);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1666","year_pubs"=>4,"year_issues"=>247);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1667","year_pubs"=>2,"year_issues"=>226);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1668","year_pubs"=>1,"year_issues"=>220);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1669","year_pubs"=>3,"year_issues"=>251);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1670","year_pubs"=>3,"year_issues"=>245);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1671","year_pubs"=>1,"year_issues"=>222);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1672","year_pubs"=>2,"year_issues"=>227);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1673","year_pubs"=>1,"year_issues"=>226);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1674","year_pubs"=>3,"year_issues"=>229);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1675","year_pubs"=>2,"year_issues"=>224);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1676","year_pubs"=>4,"year_issues"=>260);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1677","year_pubs"=>5,"year_issues"=>269);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1678","year_pubs"=>5,"year_issues"=>253);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1679","year_pubs"=>14,"year_issues"=>420);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1680","year_pubs"=>22,"year_issues"=>367);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1681","year_pubs"=>33,"year_issues"=>749);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1682","year_pubs"=>18,"year_issues"=>748);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1683","year_pubs"=>7,"year_issues"=>529);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1684","year_pubs"=>5,"year_issues"=>298);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1685","year_pubs"=>6,"year_issues"=>315);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1686","year_pubs"=>3,"year_issues"=>288);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1687","year_pubs"=>4,"year_issues"=>292);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1688","year_pubs"=>11,"year_issues"=>349);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1689","year_pubs"=>13,"year_issues"=>356);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1690","year_pubs"=>7,"year_issues"=>270);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1691","year_pubs"=>11,"year_issues"=>340);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1692","year_pubs"=>10,"year_issues"=>383);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1693","year_pubs"=>7,"year_issues"=>393);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1694","year_pubs"=>10,"year_issues"=>390);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1695","year_pubs"=>21,"year_issues"=>522);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1696","year_pubs"=>12,"year_issues"=>654);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1697","year_pubs"=>6,"year_issues"=>448);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1698","year_pubs"=>6,"year_issues"=>540);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1699","year_pubs"=>12,"year_issues"=>575);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1700","year_pubs"=>11,"year_issues"=>890);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1701","year_pubs"=>18,"year_issues"=>1101);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1702","year_pubs"=>24,"year_issues"=>1357);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1703","year_pubs"=>16,"year_issues"=>1395);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1704","year_pubs"=>28,"year_issues"=>1813);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1705","year_pubs"=>38,"year_issues"=>1969);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1706","year_pubs"=>30,"year_issues"=>1912);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1707","year_pubs"=>22,"year_issues"=>2097);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1708","year_pubs"=>27,"year_issues"=>2264);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1709","year_pubs"=>24,"year_issues"=>2169);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1710","year_pubs"=>33,"year_issues"=>2870);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1711","year_pubs"=>45,"year_issues"=>2761);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1712","year_pubs"=>45,"year_issues"=>2718);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1713","year_pubs"=>24,"year_issues"=>2463);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1714","year_pubs"=>27,"year_issues"=>2228);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1715","year_pubs"=>40,"year_issues"=>2160);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1716","year_pubs"=>44,"year_issues"=>2036);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1717","year_pubs"=>23,"year_issues"=>2098);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1718","year_pubs"=>27,"year_issues"=>2205);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1719","year_pubs"=>48,"year_issues"=>2607);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1720","year_pubs"=>49,"year_issues"=>6551);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1721","year_pubs"=>47,"year_issues"=>6739);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1722","year_pubs"=>57,"year_issues"=>6975);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1723","year_pubs"=>51,"year_issues"=>7260);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1724","year_pubs"=>59,"year_issues"=>7188);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1725","year_pubs"=>34,"year_issues"=>6508);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1726","year_pubs"=>46,"year_issues"=>6873);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1727","year_pubs"=>61,"year_issues"=>10515);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1728","year_pubs"=>50,"year_issues"=>10340);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1729","year_pubs"=>43,"year_issues"=>10158);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1730","year_pubs"=>36,"year_issues"=>9540);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1731","year_pubs"=>37,"year_issues"=>7476);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1732","year_pubs"=>39,"year_issues"=>7169);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1733","year_pubs"=>37,"year_issues"=>7369);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1734","year_pubs"=>40,"year_issues"=>7208);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1735","year_pubs"=>43,"year_issues"=>7921);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1736","year_pubs"=>44,"year_issues"=>8133);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1737","year_pubs"=>48,"year_issues"=>7996);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1738","year_pubs"=>42,"year_issues"=>7975);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1739","year_pubs"=>43,"year_issues"=>8432);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1740","year_pubs"=>45,"year_issues"=>8291);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1741","year_pubs"=>49,"year_issues"=>7735);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1742","year_pubs"=>44,"year_issues"=>3953);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1743","year_pubs"=>48,"year_issues"=>4670);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1744","year_pubs"=>54,"year_issues"=>4537);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1745","year_pubs"=>51,"year_issues"=>4824);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1746","year_pubs"=>49,"year_issues"=>3685);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1747","year_pubs"=>44,"year_issues"=>3930);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1748","year_pubs"=>41,"year_issues"=>3852);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1749","year_pubs"=>44,"year_issues"=>3387);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1750","year_pubs"=>42,"year_issues"=>3661);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1751","year_pubs"=>48,"year_issues"=>4194);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1752","year_pubs"=>46,"year_issues"=>4646);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1753","year_pubs"=>44,"year_issues"=>6993);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1754","year_pubs"=>42,"year_issues"=>7040);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1755","year_pubs"=>50,"year_issues"=>7269);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1756","year_pubs"=>55,"year_issues"=>7967);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1757","year_pubs"=>58,"year_issues"=>8202);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1758","year_pubs"=>47,"year_issues"=>8292);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1759","year_pubs"=>56,"year_issues"=>11326);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1760","year_pubs"=>57,"year_issues"=>10823);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1761","year_pubs"=>53,"year_issues"=>11151);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1762","year_pubs"=>60,"year_issues"=>12539);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1763","year_pubs"=>67,"year_issues"=>15328);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1764","year_pubs"=>63,"year_issues"=>17232);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1765","year_pubs"=>64,"year_issues"=>19262);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1766","year_pubs"=>68,"year_issues"=>19017);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1767","year_pubs"=>64,"year_issues"=>20514);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1768","year_pubs"=>75,"year_issues"=>16657);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1769","year_pubs"=>84,"year_issues"=>15893);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1770","year_pubs"=>91,"year_issues"=>14592);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1771","year_pubs"=>90,"year_issues"=>13670);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1772","year_pubs"=>90,"year_issues"=>14586);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1773","year_pubs"=>91,"year_issues"=>15033);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1774","year_pubs"=>107,"year_issues"=>18231);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1775","year_pubs"=>125,"year_issues"=>23130);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1776","year_pubs"=>118,"year_issues"=>22083);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1777","year_pubs"=>107,"year_issues"=>21831);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1778","year_pubs"=>119,"year_issues"=>22233);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1779","year_pubs"=>112,"year_issues"=>23716);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1780","year_pubs"=>107,"year_issues"=>23246);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1781","year_pubs"=>113,"year_issues"=>22800);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1782","year_pubs"=>104,"year_issues"=>24048);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1783","year_pubs"=>121,"year_issues"=>29343);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1784","year_pubs"=>136,"year_issues"=>34911);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1785","year_pubs"=>157,"year_issues"=>53229);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1786","year_pubs"=>160,"year_issues"=>65355);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1787","year_pubs"=>174,"year_issues"=>73319);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1788","year_pubs"=>188,"year_issues"=>79839);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1789","year_pubs"=>189,"year_issues"=>81033);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1790","year_pubs"=>184,"year_issues"=>82814);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1791","year_pubs"=>196,"year_issues"=>79650);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1792","year_pubs"=>216,"year_issues"=>71908);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1793","year_pubs"=>239,"year_issues"=>79671);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1794","year_pubs"=>239,"year_issues"=>142975);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1795","year_pubs"=>282,"year_issues"=>122548);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1796","year_pubs"=>291,"year_issues"=>125514);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1797","year_pubs"=>298,"year_issues"=>135726);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1798","year_pubs"=>329,"year_issues"=>130545);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1799","year_pubs"=>322,"year_issues"=>125026);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1800","year_pubs"=>347,"year_issues"=>129461);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1801","year_pubs"=>308,"year_issues"=>136895);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1802","year_pubs"=>311,"year_issues"=>147653);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1803","year_pubs"=>333,"year_issues"=>144567);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1804","year_pubs"=>355,"year_issues"=>121872);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1805","year_pubs"=>326,"year_issues"=>116880);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1806","year_pubs"=>327,"year_issues"=>113954);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1807","year_pubs"=>383,"year_issues"=>112625);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1808","year_pubs"=>413,"year_issues"=>114445);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1809","year_pubs"=>429,"year_issues"=>121207);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1810","year_pubs"=>467,"year_issues"=>131514);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1811","year_pubs"=>435,"year_issues"=>136203);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1812","year_pubs"=>440,"year_issues"=>141965);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1813","year_pubs"=>474,"year_issues"=>146878);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1814","year_pubs"=>474,"year_issues"=>140116);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1815","year_pubs"=>476,"year_issues"=>155080);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1816","year_pubs"=>482,"year_issues"=>163578);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1817","year_pubs"=>514,"year_issues"=>169683);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1818","year_pubs"=>524,"year_issues"=>180463);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1819","year_pubs"=>581,"year_issues"=>181224);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1820","year_pubs"=>594,"year_issues"=>183684);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1821","year_pubs"=>580,"year_issues"=>108890);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1822","year_pubs"=>606,"year_issues"=>119223);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1823","year_pubs"=>663,"year_issues"=>115129);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1824","year_pubs"=>720,"year_issues"=>121275);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1825","year_pubs"=>765,"year_issues"=>111442);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1826","year_pubs"=>795,"year_issues"=>111050);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1827","year_pubs"=>918,"year_issues"=>115473);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1828","year_pubs"=>976,"year_issues"=>130563);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1829","year_pubs"=>1013,"year_issues"=>125321);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1830","year_pubs"=>1164,"year_issues"=>124579);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1831","year_pubs"=>1035,"year_issues"=>129783);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1832","year_pubs"=>1135,"year_issues"=>130088);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1833","year_pubs"=>1157,"year_issues"=>128168);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1834","year_pubs"=>1126,"year_issues"=>131114);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1835","year_pubs"=>1102,"year_issues"=>133881);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1836","year_pubs"=>1126,"year_issues"=>129891);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1837","year_pubs"=>1068,"year_issues"=>136707);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1838","year_pubs"=>1159,"year_issues"=>137985);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1839","year_pubs"=>1257,"year_issues"=>140266);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1840","year_pubs"=>1619,"year_issues"=>146662);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1841","year_pubs"=>1437,"year_issues"=>133404);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1842","year_pubs"=>1350,"year_issues"=>138795);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1843","year_pubs"=>1307,"year_issues"=>137876);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1844","year_pubs"=>1559,"year_issues"=>144936);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1845","year_pubs"=>1471,"year_issues"=>156252);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1846","year_pubs"=>1520,"year_issues"=>163964);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1847","year_pubs"=>1497,"year_issues"=>160969);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1848","year_pubs"=>1770,"year_issues"=>178015);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1849","year_pubs"=>1580,"year_issues"=>191683);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1850","year_pubs"=>1654,"year_issues"=>213437);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1851","year_pubs"=>1705,"year_issues"=>219445);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1852","year_pubs"=>2142,"year_issues"=>231287);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1853","year_pubs"=>1835,"year_issues"=>254017);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1854","year_pubs"=>1941,"year_issues"=>274916);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1855","year_pubs"=>2066,"year_issues"=>273504);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1856","year_pubs"=>2058,"year_issues"=>278488);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1857","year_pubs"=>2015,"year_issues"=>289549);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1858","year_pubs"=>2021,"year_issues"=>308598);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1859","year_pubs"=>2022,"year_issues"=>309608);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1860","year_pubs"=>2316,"year_issues"=>315916);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1861","year_pubs"=>2333,"year_issues"=>310095);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1862","year_pubs"=>2074,"year_issues"=>304568);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1863","year_pubs"=>2114,"year_issues"=>300014);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1864","year_pubs"=>2076,"year_issues"=>313091);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1865","year_pubs"=>2371,"year_issues"=>326610);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1866","year_pubs"=>2192,"year_issues"=>310877);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1867","year_pubs"=>2146,"year_issues"=>306638);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1868","year_pubs"=>2299,"year_issues"=>313549);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1869","year_pubs"=>2381,"year_issues"=>319277);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1870","year_pubs"=>2277,"year_issues"=>332865);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1871","year_pubs"=>2486,"year_issues"=>353249);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1872","year_pubs"=>2649,"year_issues"=>374837);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1873","year_pubs"=>4531,"year_issues"=>382806);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1874","year_pubs"=>3684,"year_issues"=>377841);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1875","year_pubs"=>2773,"year_issues"=>367392);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1876","year_pubs"=>6915,"year_issues"=>374085);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1877","year_pubs"=>2302,"year_issues"=>303542);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1878","year_pubs"=>2382,"year_issues"=>303151);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1879","year_pubs"=>2481,"year_issues"=>296460);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1880","year_pubs"=>2611,"year_issues"=>309228);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1881","year_pubs"=>2628,"year_issues"=>311420);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1882","year_pubs"=>2381,"year_issues"=>315295);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1883","year_pubs"=>2327,"year_issues"=>326092);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1884","year_pubs"=>2498,"year_issues"=>340576);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1885","year_pubs"=>2493,"year_issues"=>358759);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1886","year_pubs"=>2622,"year_issues"=>368639);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1887","year_pubs"=>2565,"year_issues"=>371192);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1888","year_pubs"=>2845,"year_issues"=>384913);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1889","year_pubs"=>2882,"year_issues"=>398215);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1890","year_pubs"=>2818,"year_issues"=>405090);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1891","year_pubs"=>2656,"year_issues"=>394649);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1892","year_pubs"=>2839,"year_issues"=>397792);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1893","year_pubs"=>2681,"year_issues"=>397049);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1894","year_pubs"=>2574,"year_issues"=>399124);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1895","year_pubs"=>2563,"year_issues"=>390065);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1896","year_pubs"=>2613,"year_issues"=>385486);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1897","year_pubs"=>2484,"year_issues"=>378157);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1898","year_pubs"=>2624,"year_issues"=>394417);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1899","year_pubs"=>2532,"year_issues"=>395155);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1900","year_pubs"=>2557,"year_issues"=>393612);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1901","year_pubs"=>2361,"year_issues"=>369771);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1902","year_pubs"=>2175,"year_issues"=>356452);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1903","year_pubs"=>2180,"year_issues"=>346061);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1904","year_pubs"=>2154,"year_issues"=>342463);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1905","year_pubs"=>2154,"year_issues"=>344095);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1906","year_pubs"=>2185,"year_issues"=>339788);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1907","year_pubs"=>2066,"year_issues"=>338678);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1908","year_pubs"=>2139,"year_issues"=>343451);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1909","year_pubs"=>2025,"year_issues"=>351409);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1910","year_pubs"=>2011,"year_issues"=>348254);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1911","year_pubs"=>2015,"year_issues"=>333826);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1912","year_pubs"=>2003,"year_issues"=>329372);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1913","year_pubs"=>1916,"year_issues"=>319466);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1914","year_pubs"=>1981,"year_issues"=>321729);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1915","year_pubs"=>1813,"year_issues"=>318060);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1916","year_pubs"=>1824,"year_issues"=>314615);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1917","year_pubs"=>1962,"year_issues"=>318464);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1918","year_pubs"=>2036,"year_issues"=>325154);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1919","year_pubs"=>1772,"year_issues"=>318761);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1920","year_pubs"=>1623,"year_issues"=>307336);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1921","year_pubs"=>1615,"year_issues"=>296367);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1922","year_pubs"=>1513,"year_issues"=>285446);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1923","year_pubs"=>1355,"year_issues"=>219430);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1924","year_pubs"=>1293,"year_issues"=>215233);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1925","year_pubs"=>1306,"year_issues"=>215906);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1926","year_pubs"=>1285,"year_issues"=>218415);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1927","year_pubs"=>1272,"year_issues"=>212477);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1928","year_pubs"=>1261,"year_issues"=>204501);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1929","year_pubs"=>1254,"year_issues"=>207519);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1930","year_pubs"=>1187,"year_issues"=>208168);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1931","year_pubs"=>1183,"year_issues"=>204492);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1932","year_pubs"=>1263,"year_issues"=>204006);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1933","year_pubs"=>1192,"year_issues"=>194566);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1934","year_pubs"=>1760,"year_issues"=>194117);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1935","year_pubs"=>2972,"year_issues"=>202592);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1936","year_pubs"=>3480,"year_issues"=>210072);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1937","year_pubs"=>3185,"year_issues"=>210118);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1938","year_pubs"=>2511,"year_issues"=>205878);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1939","year_pubs"=>2270,"year_issues"=>202425);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1940","year_pubs"=>2099,"year_issues"=>197797);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1941","year_pubs"=>1601,"year_issues"=>185263);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1942","year_pubs"=>1152,"year_issues"=>176554);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1943","year_pubs"=>1004,"year_issues"=>175403);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1944","year_pubs"=>1070,"year_issues"=>176406);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1945","year_pubs"=>1887,"year_issues"=>191055);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1946","year_pubs"=>1495,"year_issues"=>231976);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1947","year_pubs"=>1079,"year_issues"=>175893);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1948","year_pubs"=>979,"year_issues"=>171674);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1949","year_pubs"=>1000,"year_issues"=>177445);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1950","year_pubs"=>1107,"year_issues"=>187002);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1951","year_pubs"=>1174,"year_issues"=>193815);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1952","year_pubs"=>1205,"year_issues"=>201758);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1953","year_pubs"=>1202,"year_issues"=>194274);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1954","year_pubs"=>991,"year_issues"=>180446);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1955","year_pubs"=>940,"year_issues"=>175812);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1956","year_pubs"=>1045,"year_issues"=>181643);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1957","year_pubs"=>1078,"year_issues"=>185023);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1958","year_pubs"=>1019,"year_issues"=>179296);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1959","year_pubs"=>926,"year_issues"=>175873);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1960","year_pubs"=>837,"year_issues"=>182139);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1961","year_pubs"=>871,"year_issues"=>184656);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1962","year_pubs"=>960,"year_issues"=>214517);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1963","year_pubs"=>1028,"year_issues"=>213622);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1964","year_pubs"=>985,"year_issues"=>220717);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1965","year_pubs"=>993,"year_issues"=>223963);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1966","year_pubs"=>979,"year_issues"=>224657);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1967","year_pubs"=>1027,"year_issues"=>221044);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1968","year_pubs"=>1193,"year_issues"=>223304);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1969","year_pubs"=>1247,"year_issues"=>219701);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1970","year_pubs"=>1118,"year_issues"=>217765);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1971","year_pubs"=>1058,"year_issues"=>216456);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1972","year_pubs"=>1150,"year_issues"=>217751);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1973","year_pubs"=>1125,"year_issues"=>211915);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1974","year_pubs"=>1004,"year_issues"=>177238);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1975","year_pubs"=>1035,"year_issues"=>174058);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1976","year_pubs"=>1088,"year_issues"=>168491);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1977","year_pubs"=>890,"year_issues"=>163868);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1978","year_pubs"=>879,"year_issues"=>162721);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1979","year_pubs"=>851,"year_issues"=>162026);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1980","year_pubs"=>813,"year_issues"=>156280);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1981","year_pubs"=>823,"year_issues"=>152828);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1982","year_pubs"=>797,"year_issues"=>141470);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1983","year_pubs"=>738,"year_issues"=>137030);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1984","year_pubs"=>690,"year_issues"=>133539);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1985","year_pubs"=>662,"year_issues"=>127357);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1986","year_pubs"=>612,"year_issues"=>121747);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1987","year_pubs"=>563,"year_issues"=>112675);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1988","year_pubs"=>565,"year_issues"=>110661);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1989","year_pubs"=>510,"year_issues"=>102595);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1990","year_pubs"=>485,"year_issues"=>96507);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1991","year_pubs"=>485,"year_issues"=>92656);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1992","year_pubs"=>477,"year_issues"=>82402);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1993","year_pubs"=>460,"year_issues"=>77915);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1994","year_pubs"=>390,"year_issues"=>73082);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1995","year_pubs"=>355,"year_issues"=>67220);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1996","year_pubs"=>329,"year_issues"=>62123);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1997","year_pubs"=>299,"year_issues"=>57917);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1998","year_pubs"=>304,"year_issues"=>55698);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"1999","year_pubs"=>293,"year_issues"=>53102);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"2000","year_pubs"=>292,"year_issues"=>49335);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"2001","year_pubs"=>281,"year_issues"=>42149);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"2002","year_pubs"=>214,"year_issues"=>40044);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"2003","year_pubs"=>202,"year_issues"=>37243);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"2004","year_pubs"=>186,"year_issues"=>31698);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"2005","year_pubs"=>131,"year_issues"=>27994);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"2006","year_pubs"=>129,"year_issues"=>26893);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"2007","year_pubs"=>112,"year_issues"=>24724);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"2008","year_pubs"=>96,"year_issues"=>20694);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"2009","year_pubs"=>75,"year_issues"=>14747);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"2010","year_pubs"=>59,"year_issues"=>10621);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"2011","year_pubs"=>43,"year_issues"=>6416);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"2012","year_pubs"=>41,"year_issues"=>3896);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"2013","year_pubs"=>25,"year_issues"=>2898);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"2014","year_pubs"=>5,"year_issues"=>91);
array_push($yearArray, $yearInfo);
$yearInfo = array("this_year"=>"2015","year_pubs"=>1,"year_issues"=>14);
array_push($yearArray, $yearInfo);


/***************************************************************/
$encoded = json_encode($yearArray);
die($encoded);


?>