<!--AJE 2016-05-09 16:59:00 FOUNDATION HELP ELEMENT
help_selection_datepicker_color_key-->

 <ul id="datepicker_color_key" style="list-style-type:none;" class="reveal-modal [expand, xlarge, large, medium, small]" data-animation="fade" data-animationspeed="300">
    <li><a class="close-reveal-modal">&#215;</a></li>
    <li>
        <span class="publication_date" style="font-weight:bold;">&nbsp;confirmed dates:&nbsp;</span>
        publication date specified in issue data from vendor/provider
    </li>
    <li>
        <span class="iconDate_publication_date" style="font-weight:bold;">&nbsp;assumed dates:&nbsp;</span>
        publication date generated by ICON system, based on publication frequency and first-last date held by organization
    </li>
    <li>
        <span class="selected_publication_date" style="font-weight:bold;">&nbsp;date selected:&nbsp;</span>
        click dated tab for details about this date
    </li>
 </ul>
<!--end help_selection_datepicker_color_key.php-->