/*-------------------------------------------------------------*/
/* J Q U E R Y   I N I T I A L I Z A T I O N   F U N C T I O N
/*-------------------------------------------------------------*/
$(function() {
	selectedPubIdWithoutSpace = unescape(selectedPubIdWithoutSpace);
	selectedPubId = selectedPubId.replace('%20', '');
	$.get("get_publication_info.php", { 'pub_id': selectedPubIdWithoutSpace }, displayTitleInfo);
	populateStartupMonths();
	//Change year via dropdown
	$('#year_option').change(function() {
		$('#issue_date_display').html('');
		$('#inner_issue_info_display').html('').hide();
		$('#loading-issue-info').attr('class', 'loading-issue-info-visible');
		clearAvailableMonths();
		clearRepositoryInfo();
		changeYearFlag = true;
		selectedYear = $('#year_option :selected').text();
		whiteOutCalendar();
		styleAvailableMonthBoxes();
		$('option:selected').css('backgroundColor', '#4E4F7F').css('color', '#DFE2E6').css('fontWeight', 'bold');
		$('option:not(:selected)').css('backgroundColor', '#ADBD90').css('color','#00224C').css('fontWeight', 'normal');
	});
	$('.month_box').addClass('month_box_not_available');
	$('.month_box').click(function() {
		$('option:selected').css('backgroundColor', '#4E4F7F').css('color', '#DFE2E6').css('fontWeight', 'bold');
		$('option:not(:selected)').css('backgroundColor', '#ADBD90').css('color','#00224C').css('fontWeight', 'normal');
		clearRepositoryInfo();
		//Clear and hide issue info display
		$('#issue_date_display').html('');
		$('#inner_issue_info_display').html('').hide();
		$('#loading-issue-info').attr('class', 'loading-issue-info-visible');
		//Deselect all other available month boxes
		var tempMonthBoxId = tempMonthBox = null;
		for (var m in availableMonths) {
			tempMonthBoxId = availableMonths[m];
			tempMonthBox = $('#month_control_wrapper').find('#' + tempMonthBoxId);
			tempMonthBox[0].className = "month_box month_box_available";				
		}		
		//Apply 'selected' class to this month box if there are available issues
		var tempClass = this.className;
		if (tempClass.search('month_box_available') != -1) {
			this.className = 'month_box month_box_available month_box_selected';
		}
		selectedMonth = this.id;
		selectedMonth = getMonthNumber(selectedMonth);
		whiteOutCalendar();
		populateAvailableDays();
	});
	$(".timeline").delegate('.count', 'click', function(){
		$('#issue_date_display').html('');	
		$('#inner_issue_info_display').html('').hide();
		$('#loading-issue-info').attr('class', 'loading-issue-info-visible');
		$('#year_option').attr('disabled', true);
		clearRepositoryInfo();
		clearAvailableMonths();
		changeYearFlag = true;
		selectedYear = $(this).attr('id');
		whiteOutCalendar();
		styleAvailableMonthBoxes();
		$('option:selected').css('backgroundColor', '#4E4F7F').css('color', '#DFE2E6').css('fontWeight', 'bold');
		$('option:not(:selected)').css('backgroundColor', '#ADBD90').css('color','#00224C').css('fontWeight', 'normal');
	});
	$(".timeline").delegate('.count', 'mouseover', function(){
		//Bar turns light green on on mouseOver event
		$(this).css('backgroundColor', '#ADBD90');
	});
	$(".timeline").delegate('.count', 'mouseout', function(){
		//Bar returns to blue on mouseOut event
		$(this).css('backgroundColor', '#4E4F7F');
	});
	$('.page_link').click(function() {
		$('.page_link').css('fontWeight', 'normal');
		$(this).css('fontWeight', 'bold');
	});
});
/*---------------------------------------------------------------------------------------------------------*/
/* jQuery paginateTable() plugin
/* Copyright 2010-2011 by Matthew Page
/* Original source at https://github.com/mattpage/jquery.paginateTable/blob/master/jquery.paginatetable.js
/*---------------------------------------------------------------------------------------------------------*/
$.fn.paginateTable = function(options) {
      var settings = jQuery.extend({
          rowsPerPage: 5,               /* the number of rows that comprise a page */
          nextPage: ".nextPage", 		/* selector for "Next Page" dom element. Click to change page. */
          prevPage: ".prevPage",		/* selector for "Previous Page" dom element. Click to change page. */ 
          currentPage: ".currentPage",	/* selector for "Current Page" dom element. Display only. */
          totalPages: ".totalPages",	/* selector for "Total Pages" dom element. Display only. */
          pageNumbers: ".pageNumbers",  /* selector for container for autogenerated page number links */
          pager: ".pager",		        /* selector for container of all paging dom elements */
          autoHidePager: false		    /* hides the pager (see selector above) if there is only a single page */
      }, options || {});
  
      return this.each(function(){
          
          var table = $(this);
          var pager = $(settings.pager);
          var nextPage = pager.find(settings.nextPage);
          var prevPage = pager.find(settings.prevPage);
          var currentPage = pager.find(settings.currentPage);
          nextPage.unbind('click');
          nextPage.click(function(){
                  var pageNum = getCurrentPage(currentPage.text());
                  $('h4:contains("Repository Information")').remove();
									$('#repository_info').remove();
                  displayPage(table, pageNum+1, settings);
                  return false;
              });
          prevPage.unbind('click');
          prevPage.click(function(){
                  var pageNum = getCurrentPage(currentPage.text());
                  $('h4:contains("Repository Information")').remove();
									$('#repository_info').remove();
                  displayPage(table, pageNum-1, settings);
                  return false;
              });
          
          displayPage(table, getCurrentPage(currentPage.text()), settings);
      });
  };
  function getCurrentPage(pageText){
      var pageNum = parseInt(pageText,10);
      if (isNaN(pageNum)){
          pageNum = 0;
      }
      return Math.max(1, pageNum);
  }

  function displayPage(table, pageNum, settings){
      pageNum = Math.max(1, pageNum);
      if (settings.rowsPerPage > 0){
          var rows = table.find("tbody tr");
          var totalPages = Math.ceil(rows.size() / settings.rowsPerPage);
          if (settings.autoHidePager && totalPages <= 1){
              $(settings.pager).hide();
          }
          else if (totalPages > 0){
              
              pageNum = Math.min(pageNum, totalPages);
              var rowStartIndex = (pageNum - 1) * settings.rowsPerPage;
              var rowEndIndex = pageNum * settings.rowsPerPage;
              $.each(rows, function(index, row){
                  if (index >= rowStartIndex && index < rowEndIndex){
                      $(row).show();
                  }
                  else{
                      $(row).hide();
                  }
              });
              
              var pager = $(settings.pager);
              pager.find(settings.currentPage).text(pageNum);
              pager.find(settings.totalPages).text(totalPages);
              
              /*-----------------------------------------------------*/
              /* Customized this section to simulate disabled 'Prev' 
              /* and 'Next'links on first and last page of results
              /*-----------------------------------------------------*/
              if(pager.find(settings.currentPage).text() == 1) {
              	 $('.prevPage').css('textDecoration', 'none');
              } else {
              	 $('.prevPage').css('textDecoration', 'underline');
              }
              if(pager.find(settings.currentPage).text() == totalPages) {
              	 $('.nextPage').css('textDecoration', 'none');
              } else {
              	 $('.nextPage').css('textDecoration', 'underline');
              }
              /*------------------------------------------------------------------------*/              
              
              var pageNumbers = pager.find(settings.pageNumbers);
              if (pageNumbers.size() > 0){
                   pageNumbers.empty();
                   for(var i = 1; i <= totalPages; i++) {
                       pageNumbers.append("<a href='#' id='" + i + "'>" + i + "</a>");
                   }
       
                   pageNumbers.children('a').click(function(){
                       displayPage(table, $(this).attr("id"), settings);
                       return false;
                   });
              }
          }
          
      }
  }
/*-------------------------------*/
/* O T H E R   F U N C T I O N S
/*-------------------------------*/	
function displayTitleInfo(results, textStatus) {
	if ((results.search(/Error/i) != -1) || (results.search(/\<b>Notice/i) != -1 )) {
		document.writeln(results);
	} else {
		var tempPubId = tempPubTitle = tempPubTitleAlt = tempPubCity = tempPubState = tempCountry = tempFrequencyIdCode = null;
		var tempPubBgnDate = tempPubEndDate = tempDate260C = tempFrequency310 = tempFormerFrequency321 = tempDate362 = null;
		var tempNumberingNote515 = tempSummary520 = tempDescriptionNote588 = tempRefDataBody = tempRefDataTitle = tempRefDataURI = tempRefSourceTitle = tempShowFullText = null;
		var addRefString = '';
		var data = JSON.parse(results);
		if (data.pubTitle == "") {	
			$('#sidebar').prepend('<div class="block"><h4>Title Information</h4></div><div class="not_icon_title" id="title_info"><p>This title does not appear in ICON.</p></div>');
			$('#loading-calendar').html('<p>Sorry, there are no issues in ICON for this title.</p>');
			$('#loading-issue-info').hide();
		} else {
			tempPubId = data.pubId;
			tempMarc001 = data.marc001.replace(/\\/g,'');
			tempMarc001 = tempMarc001.replace(/^ocm/,'');
			tempPubTitle = data.pubTitle;
			document.title = document.title + " for " + tempPubTitle;
			tempPubTitleAlt = data.pubTitleAlt;
			tempPubCity = data.pubCity;
			tempPubState = data.countryId.substr(0,2).toUpperCase();
			if (data.countryId.length == 3 && data.countryId.substr(2,1) == 'U' && data.countryId.substr(2,1) == 'C') {
				//Country is US or Canada 
				tempCountry = data.countryId.substr(2,1);
			} else {
				//Other country
				tempCountry = data.countryName;
			}
			tempFrequencyIdCode = data.frequencyIdCode;
			tempPubBgnDate = data.pubBgnDate;
			tempPubEndDate = data.pubEndDate;
			tempDate260C = data.date260C;
			tempDate260C = tempDate260C.replace(/</g,'&lt;');
			tempDate260C = tempDate260C.replace(/>/g,'&gt;');
			tempFrequency310 = data.frequency310;
			tempFrequency310 = tempFrequency310.replace(/</g,'&lt;');
			tempFrequency310 = tempFrequency310.replace(/>/g,'&gt;');
			tempFormerFrequency321 = data.formerFrequency321;
			tempFormerFrequency321 = tempFormerFrequency321.replace(/</g,'&lt;');
			tempFormerFrequency321 = tempFormerFrequency321.replace(/>/g,'&gt;');
			tempDate362 = data.date362;
			tempDate362 = tempDate362.replace(/</g,'&lt;');
			tempDate362 = tempDate362.replace(/>/g,'&gt;');
			tempNumberingNote515 = data.numberingNote515;
			tempNumberingNote515 = tempNumberingNote515.replace(/</g,'&lt;');
			tempNumberingNote515 = tempNumberingNote515.replace(/>/g,'&gt;');
			tempSummary520 = data.summary520;
			tempDescriptionNote588 = data.descriptionNote588;
			tempRefDataBody = data.refDataBody;
			tempRefDataTitle = data.refDataTitle;
			tempRefDataURI = data.refDataURI;
			tempRefSourceTitle = data.refSourceTitle,
			tempShowFullText = data.showFullText;
			titleInfoDisplayString += '<div class="title_section_first"><b>' + tempPubTitle + '</b></div>';
			if (tempPubTitleAlt != '') {
				titleInfoDisplayString += '<div class="title_section_first">' + tempPubTitleAlt + '</div>'; 
			}		
			if (tempCountry == 'u' || tempCountry == 'c') {
				//US or Canada, so display city and state but not country name
				titleInfoDisplayString += '<div class="title_section_first">' + tempPubCity + ', ' + tempPubState + '</div>';
			} else {
				//Other country, so display city and country name, but not state
				titleInfoDisplayString += '<div class="title_section_first">' + tempPubCity + ', ' + tempCountry + '</div>';
			}
			if (tempRefDataURI != '' && tempRefDataURI != null) {
				//If available, display additional reference information for title
				if (tempShowFullText == "1") {
					//Display additional reference text as well as link
					addRefString = 'From ' + tempRefSourceTitle + ':<div class="add_ref_text">' + tempRefDataBody + '</div><a href="' + tempRefDataURI + '" target="_blank">' + tempRefDataTitle +  '</a><br />';
				} else {
					//Display additional reference link only
					addRefString = 'Related title on ' + tempRefSourceTitle + ':<br /><a href="' + tempRefDataURI + '" class="add_ref_link" target="_blank">' + tempRefDataTitle +  '</a><br />';
				}
				titleInfoDisplayString += '<div id="add_ref">' + addRefString + '</div><div class="title_section">ID: &nbsp;</span>' + tempPubId + '</div>';
			} else {
				titleInfoDisplayString += '<div class="title_section">ID: &nbsp;</span>' + tempPubId + '</div>';
			}
			titleInfoDisplayString += '<div class="title_section">PUBLICATION:<ul>';
			if (tempFrequency310 != '') {
				titleInfoDisplayString += '<li>' + tempFrequency310 + '</li>'; 
			}
			if (tempFormerFrequency321 != '') {
				titleInfoDisplayString += '<li>' + tempFormerFrequency321 + '</li>';
			}
			//Publication dates
			if (tempDate362 != '') {
				titleInfoDisplayString += '<li>' + tempDate362 + '</li>'; 
			} else if (tempDate260C != '') {
				if (tempDate260C.search(/^-/) != -1) {
					titleInfoDisplayString += '<li>' + tempPubBgnDate + tempDate260C + '</li>';
				} else if (tempDate260C.search(/-$/) != -1){
					titleInfoDisplayString += '<li>' + tempDate260C + tempPubEndDate + '</li>';
				} else {
					titleInfoDisplayString += '<li>BEGIN: ' + tempPubBgnDate + '</li>' + 
											  '<li>END: ' + tempPubEndDate + '</li>' + 
										      '<li>DATE 260C: ' + tempDate260C + '</li>';
				}
			} else if ((tempPubBgnDate != '') || (tempPubEndDate != '')) {
				titleInfoDisplayString += '<li>BEGIN: ' + tempPubBgnDate + '</li>' + 
										  '<li>END: ' + tempPubEndDate + '</li>';
			}
			titleInfoDisplayString += '</ul></div>';
			if (tempNumberingNote515 != '' || tempSummary520 != '' || tempDescriptionNote588 != '') {
				titleInfoDisplayString += '<div class="title_section">NOTES:<ul>';
				if (tempNumberingNote515 != '') {
					titleInfoDisplayString += '<li>' + tempNumberingNote515 + '</li>'; 
				}
				if (tempSummary520 != '') {
					titleInfoDisplayString += '<li>' + tempSummary520 + '</li>'; 
				}
				if (tempDescriptionNote588 != '') {
					titleInfoDisplayString += '<li>' + tempDescriptionNote588 + '</li>'; 
				}
				titleInfoDisplayString += '</ul></div>';
			}
			if (tempMarc001 != '') {
				titleInfoDisplayString += '<!--Andy rmvd this for Amys demo to CRL Annual Meeting 17 Apr 2012';
				titleInfoDisplayString += '<span class="title_info_label">OCLC: &nbsp;</span>' + tempMarc001 + '<br />';
				titleInfoDisplayString += 'end AJE-->';
			}
			$('#sidebar').prepend('<div class="block"><h4>Title Information</h4></div><div class="block" id="title_info"><p>' + titleInfoDisplayString + '</p></div>');
			$('#loading-calendar').html('<p>Searching for issues&nbsp; . . . &nbsp;&nbsp;<img src="loading-calendar.gif" /></p>');
			$('#loading-calendar').attr('class', 'loading-calendar-visible');
			$.get("get_all_issues.php", { 'selectedPubId': selectedPubId }, populateAllIssues);
		}
	}
}
function populateStartupMonths() {
	tempAvailableMonthsObject = new Object();
	for (var i = 0; i < monthNameArray.length; i++) {
		tempAvailableMonthsObject[i] = monthNameArray[i];
	}
}
function populateAllIssues(results, textStatus) {
	if ((results.search(/Error/i) != -1) || (results.search(/\<b>Notice/i) != -1 )) {
		document.writeln(results);
	} else {
		var data = JSON.parse(results);
		allIssues = data.allIssues;
	}
	populateIssueCounts();
}
function populateIssueCounts() {
	if (allIssues[0] != null) {
		var tmpMonths = new Object();
		var tmpObject = null;
		issueCounts = new Object();
		var currYr = currDate = tmpDate = currMonth = tmpMonth = null;
		var tmpCount = yearCounter = monthCounter = 0;
		var tmpYr = allIssues[0]['pubDate'].substr(0,4);
		var tmpFirstYear = tmpYr;
		var tmpFirstMonth = allIssues[0]['pubDate'].substr(5,2);
		for (var issue in allIssues) {
			currYr = allIssues[issue]['pubDate'].substr(0,4);
			currDate = allIssues[issue]['pubDate'];
			currMonth = allIssues[issue]['pubDate'].substr(5,2);
			if (currYr == tmpYr) {
				if (currDate != tmpDate) {
					tmpDate = currDate;
					tmpCount++;
				}
				if (currMonth != tmpMonth) {
					tmpMonths[monthCounter] = monthNameArray[parseInt(currMonth,10)-1];
					tmpMonth = currMonth;
					monthCounter++;
				}
			} else {
				tmpObject = new Object();
				tmpObject.year = tmpYr;
				tmpObject.count = tmpCount;
				tmpObject.available_months = tmpMonths;
				issueCounts[yearCounter] = tmpObject;
				tmpMonths = new Object();
				tmpDate = currDate;
				monthCounter = 0;
				tmpMonth = currMonth = allIssues[issue].pubDate.substr(5,2);
				tmpMonths[monthCounter] = monthNameArray[parseInt(currMonth,10)-1];
				tmpYr = currYr;
				yearCounter++;
				monthCounter++;
				tmpCount = 1;
			}
		}
		tmpObject = new Object();
		tmpObject.year = tmpYr;
		tmpObject.count = tmpCount;
		tmpObject.available_months = tmpMonths;
		issueCounts[yearCounter] = tmpObject;
		//Get maximum year issue count for bar height calculation
		for (var c in issueCounts) {
			if (issueCounts[c].count > maxIssueCount) {
				maxIssueCount = issueCounts[c].count;
			}
		}
	}
	finishInitialization();
}
function finishInitialization() {
	if (issueCounts == null) {
		//$('#loading-calendar').html('No issues for ' + selectedPubIdWithoutSpace + " in database");
		$('#loading-calendar').html('<p>Sorry, there are no issues in ICON for this title.</p>');
		$('#loading-issue-info').hide();
		return false;	
	} else {
		startupFlag = true;
		yearBox = document.getElementById("year_option");
		selectedYear = issueCounts[0].year;
		//Populate barchart timeline
		displayDecadesBarchart();
		//Populate an array with available months for first available year
		//Month box and calendar controls are populated in the callback
		styleAvailableMonthBoxes();
	}
}
function displayDecadesBarchart() {
	var tempYear, tempYearDigit, tempDecadeDigits, tempBarchartAnchor, tempBarchartElement1, tempBarchartElement2, tempClass, tempBarSize;
	for (var i in issueCounts) {
		tempYear = issueCounts[i].year;
		tempIssueCount = issueCounts[i].count;
		tempBarSize = (tempIssueCount/maxIssueCount * 100) + "%";
		tempYearDigit = issueCounts[i].year.substr(3);
		tempClass = 'y' + tempYearDigit;
		tempDecadeDigits = tempYear.substring(0,3) + "0";
		tempBarchartAnchor = $('a:contains(' + tempDecadeDigits + ')');
		tempBarchartElement1 = tempBarchartAnchor[0].parentNode.parentNode.children[1];
		tempBarchartElement2 = document.createElement('li');
		tempBarchartElement1.appendChild(tempBarchartElement2);
		addClass(tempBarchartElement2,tempClass);
		tempBarchartElement1 = document.createElement('a');
		tempBarchartElement2.appendChild(tempBarchartElement1);
		tempBarchartElement2 = document.createElement('span');
		addClass(tempBarchartElement2, 'count');
		if (tempIssueCount == 1) {
			tempBarchartElement2.title = tempYear + " - " + tempIssueCount + " issue";
		} else {
			tempBarchartElement2.title = tempYear + " - " + tempIssueCount + " issues";
		}
		tempBarchartElement2.id = tempYear;
		tempBarchartElement2.style.height = tempBarSize;
		tempBarchartElement1.appendChild(tempBarchartElement2);
	}
}
function styleAvailableMonthBoxes() {
	var tempMonth = tempPubDate = tempMonthBoxId = tempMonthBox = tmpObject = null;
	availableMonths = new Object();
	tmpObject = getObjects(issueCounts, 'year', selectedYear)[0];
	availableMonths = tmpObject.available_months;
	for (var m in availableMonths) {
		tempMonthBoxId = availableMonths[m];
		tempMonthBox = $('#month_control_wrapper').find('#' + tempMonthBoxId);
		tempMonthBox[0].className = "month_box month_box_available";			
	}
	if (startupFlag == true || changeYearFlag == true) {
		//Calendar displays first available month for selected year
		selectedMonth = getMonthNumber(availableMonths[0]);
		tempMonthBoxId = availableMonths[0];
		tempMonthBox = $('#month_control_wrapper').find('#' + tempMonthBoxId);
		tempMonthBox[0].className = "month_box month_box_available month_box_selected";		
	}
	populateAvailableDays();
	displayFilteredYearDropdown();
	for (var i = 0; i < yearBox.options.length ; i++) {
		if (yearBox.options[i].text == selectedYear) {
			yearBox.options[i].selected = true ;
			break ;
		}
	}
	$('#year_option').attr('disabled', false);
}
function populateAvailableDays() {
	availableDays = new Object();
	var tempDefaultDate = null;
	var tmpMonthYear = selectedYear + "-" + padDate(parseInt(selectedMonth+1,10));
	availableDays = getObjects(allIssues, 'pubDate', tmpMonthYear);
	if (availableDays.length == 0) {
		//There are no available issues in selected month
		//Change calendar month without populating day array
		//No date cells will contain links
		firstDay = new Date(selectedYear, selectedMonth, 1);
		selectedDate = selectedYear + '-' + padDate(parseInt(selectedMonth+1,10)) + '-01';
		$('#datepicker_container').datepicker('setDate', firstDay);
		$('#issue_date_display').html('No issues available for this month');
		$('#loading-issue-info').hide();
	} else {
		//There are available issues in selected month
		//Change calendar month after populating day array
		//Available date cells will contain links
		tempDefaultDate = selectedDate = availableDays[0].pubDate;
		selectedDay = tempDefaultDate.substr(tempDefaultDate.length-2,2);
		selectedDay = parseInt(selectedDay, 10);
		defaultDate = new Date(selectedYear, selectedMonth, selectedDay);
		//Test whether page load occurred
		if (startupFlag == true) {
			//Page load occurred
			//Initialize datepicker, setting calendar default date to first available day in first available month and year
			$('#datepicker_container').datepicker({ changeMonth: false, 
													changeYear: false,
													defaultDate: defaultDate,
													dateFormat: 'yyyy-mm-dd',
													beforeShowDay: highlightIssueDates,
													onChangeMonthYear: function() {
														if (availableDays.length == 0) {
															$('#issue_date_display').html('No issues available for this month');
														} else {
															selectedDateFormatted = toTitleCase(monthAbbrevArray[selectedMonth]) + ' ' + parseInt(selectedDay,10) + ', ' + selectedYear;
															$('#issue_date_display').html('Issue date: &nbsp;' + selectedDateFormatted);
														}
													},
													onSelect: function(date) {
														selectedDay = date.substr(date.length-2,2);
														selectedDate = selectedYear + '-' + padDate(parseInt(selectedMonth,10)+1) + '-' + selectedDay;
														selectedDateFormatted = toTitleCase(monthAbbrevArray[selectedMonth]) + ' ' + parseInt(selectedDay,10) + ', ' + selectedYear;
														$('#issue_date_display').html('Issue date: &nbsp;' + selectedDateFormatted);
														displayFilterLinks();
													}
			});				
			startupFlag = false;
			changeYearFlag = false;
			$('#loading-calendar').attr('class', 'loading-calendar-invisible');
			selectedDateFormatted = toTitleCase(monthAbbrevArray[selectedMonth]) + ' ' + parseInt(selectedDay,10) + ', ' + selectedYear;
			$('#issue_date_display').html('Issue date: &nbsp;' + selectedDateFormatted);
			displayFilterLinks();
			$('#inner_selection_control_wrapper').show();
		} else {
			//Month or year changed in response to user selection, not page load
			//Set calendar default date to first available day in selected month and year
			$("#datepicker_container").datepicker("setDate", defaultDate);
			selectedDateFormatted = toTitleCase(monthAbbrevArray[selectedMonth]) + ' ' + parseInt(selectedDay,10) + ', ' + selectedYear;
			$('#issue_date_display').html('Issue date: &nbsp;' + selectedDateFormatted);
			displayFilterLinks();
		}
	}
}
function displayFilteredYearDropdown() {
	yearBox.options.length = 0;
	for (var i in issueCounts) {
		addOption(yearBox, issueCounts[i].year, i+1);
	}
	$('option:selected').css('backgroundColor', '#4E4F7F').css('color', '#DFE2E6');
	$('option:not(:selected)').css('backgroundColor', '#ADBD90').css('color','#00224C');
}
function highlightIssueDates(date) {
	if (availableDays.length > 0) {
		var tempDateString, tempMonth, tempDay;
		tempMonth = padDate(date.getMonth()+1);
		tempDay = padDate(date.getDate());
		tempDateString = date.getFullYear() +"-" + tempMonth + "-" + tempDay;
		var daysReturned = getObjects(availableDays, 'pubDate', tempDateString);
		if (daysReturned.length > 0) {
			if (parseInt(tempDay, 10) == selectedDay) {
				return [true, 'selected_publication_date a'];
			} else {
				return [true, 'publication_date a'];
			}
		} else {
			return [false, 'not_publication_date'];
		}
	} else {
		return [false, ''];
	}
}
function displayFilterLinks() {
	if (availableDays.length == 0) {
		$('#loading-issue-info').attr('class', 'loading-issue-info-invisible');
		$('#inner_issue_info_display').html('').hide();			
	} else {
		//Create filter links
		var tempContainer = tempDiv = tempLink = null;
		$('#inner_issue_info_display').html('');
		$('#inner_issue_info_display').append('<div></div>');
		$('h4:contains("Repository Information")').remove();
		$('#repository_info').remove();
		tempContainer = $('#inner_issue_info_display').children('div')[0];
		tempContainer.id = 'tempContainer';
		tempContainer.className = 'link_group_container';
		$('#tempContainer').append('<div>Filter by:</div><div><a id="Filter by Repository blah" href="javascript:;">Repository</a></div>');
		$('#tempContainer').append('<div><a id="Filter by Format" href="javascript:;">Format</a></div>');
		tempDiv = $('#tempContainer').children('div')[0];
		tempDiv.style.padding = '0 0 10px 0';
		tempDiv = $('#tempContainer').children('div')[1];
		tempLink = tempDiv.childNodes[0];
		tempLink.onclick = function(){
			var tmpRepId = null;
			var tmpSortedIssuesObject = new Object();
			var tmpObject = new Object();
			availableRepositories = new Object();
			var sortedIssues = allIssues.sort(compareRepositoryNames);
			tmpSortedIssuesObject = getObjects(sortedIssues, 'pubDate', selectedDate);
			for (var i in tmpSortedIssuesObject) {
				//Create list of unique repository codes from issue records with this publication date
				if (tmpSortedIssuesObject[i].repositoryId != tmpRepId) {
					tmpObject = new Object();
					tmpObject.repository_name = tmpSortedIssuesObject[i].repositoryName;
					tmpObject.repository_id = tmpSortedIssuesObject[i].repositoryId;
					availableRepositories[i] = tmpObject;
					tmpRepId = tmpSortedIssuesObject[i].repositoryId;
				}				
			}
			displayRepositoryLinks();
		};		
		tempDiv = $('#tempContainer').children('div')[2];
		tempLink = tempDiv.childNodes[0];
		tempLink.onclick = function(){
			var tmpFormat = null;
			var tmpObject = new Object();
			availableFormats = new Object();
			var sortedIssues = allIssues.sort(compareFormats);
			tmpObject = getObjects(sortedIssues, 'pubDate', selectedDate);
			tmpFormat = tmpObject[0].format;
			availableFormats[0] = tmpFormat;
			for (var i in tmpObject) {
				//Create list of unique formats from issue records with this publication date
				if (tmpObject[i].format != tmpFormat) {
					availableFormats[i] = tmpObject[i].format;
					tmpFormat = tmpObject[i].format;
				}				
			}
			displayFormatLinks();
		};
		$('#loading-issue-info').attr('class', 'loading-issue-info-invisible');
		$('#inner_issue_info_display').show();
	}
}
function displayRepositoryLinks() {
	var tempContainer = tempDiv = tempElementString = repositoryLinks = null;
	$('h4:contains("Repository Information")').remove();
	$('#repository_info').remove();
	$('#inner_issue_info_display').html('');
	//Create a 'Back' link to redisplay filter list
	$('#inner_issue_info_display').append('<div><a class="breadcrumb" href="" onclick="displayFilterLinks(); return false;">Back to filter list</a></div>');
	//Add pagination links
	$('#page_navigation').html(navigation_html);
	//Add active_page class to the first pagination link  
  $('#page_navigation .page_link:first').addClass('active_page');
  $('#inner_issue_info_display').append('<p>Please select a repository to display issue information:</p>');
	//Create repository links
	$('#inner_issue_info_display').append('<div id="temp_container" class="link_group_container"></div>');
	//$('#inner_issue_info_display').append('<div id="temp_container" class="link_group_container"><p>Please select a repository to display issue information:</p></div>');
	tempContainer = $('#inner_issue_info_display').children('div')[0];
	for (var i in availableRepositories) {
		tempElementString = '<div><a href="" id="' + availableRepositories[i].repository_id + '">' + availableRepositories[i].repository_name + '</a></div>';
		$('#temp_container').append(tempElementString);
	}
	//Populate pagination variables
	number_of_items = $('#temp_container').children().size();
	number_of_pages = Math.ceil(number_of_items/show_per_page);  
	current_link = 0;
  //Set value of hidden pagination controls
  $('#current_page').val(0);  
  $('#show_per_page').val(show_per_page);
  //Build HTML string to create pagination links
  navigation_html = '<a class="previous_link" href="javascript:previous();">Prev</a>';
  while(number_of_pages > current_link){  
  	navigation_html += '<a class="page_link" href="javascript:go_to_page(' + current_link +')" longdesc="' + current_link +'">'+ (current_link + 1) +'</a>';  
  	current_link++; 
  }  
  navigation_html += '<a class="next_link" href="javascript:next();">Next</a>';	
	 //Hide all the elements inside link container, then show only the first n as defined in show_per_page variable 
  $('#temp_container').children().css('display', 'none');    
  $('#temp_container').children().slice(0, show_per_page).css('display', 'block');
  
  $('#inner_issue_info_display').append('<div id="page_navigation">' + navigation_html + '</div>');
  //Add active_page class to the first page link  
  $('#page_navigation .page_link:first').addClass('active_page');
  if (number_of_pages > 1) {
  	$('#page_navigation').css('visibility', 'visible');
  }
  //Disable 'Previous' link at startup
  $('.previous_link').css('color', '#303030').css('textDecoration', 'none'); 
   
	repositoryLinks = $('#temp_container div a');
	for (var j = 0; j < repositoryLinks.length; j++) {
		repositoryLinks[j].onclick = function(){
		selectedRepositoryId = this.id;
			var tmpObject = new Object();
			availableIssues = new Object();
			tmpObject = getObjects(allIssues, 'pubDate', selectedDate);
			availableIssues = getObjects(tmpObject, 'repositoryId', this.id);
			availableIssues = availableIssues.sort(compareFormats);
			displayIssueInfoByRepository();
			$.get("get_repository_info.php", { 'selectedRepositoryId': selectedRepositoryId }, displayRepositoryInfo);
			return false;
		}
	}
}
function displayFormatLinks() {
	var tempContainer = tempDiv = tempElementString = formatLinks = null;
	$('h4:contains("Repository Information")').remove();
	$('#repository_info').remove();
	$('#inner_issue_info_display').html('');
	//Create a 'Back' link to redisplay filter list
	$('#inner_issue_info_display').append('<div><a class="breadcrumb" href="javascript:;" onclick="displayFilterLinks(); return false;">Back to filter list</a></div>');
	//Create repository links
	$('#inner_issue_info_display').append('<div id="temp_container" class="link_group_container"><p>Please select a format to display issue information:</p></div>');
	tempContainer = $('#inner_issue_info_display').children('div')[1];
	for (var i in availableFormats) {
		if (availableFormats[i] == "format unspecified/unknown") {
		  tempElementString = '<div><a href="" id="' + availableFormats[i] + '">Unspecified or unknown</a></div>';
		} else if (availableFormats[i] == "Digital pdf") {
			tempElementString = '<div><a href="" id="Digital pdf">Digital (pdf)</a></div>';
		} else {
			tempElementString = '<div><a href="" id="' + availableFormats[i] + '">' + availableFormats[i] + '</a></div>';
		}
		$('#temp_container').append(tempElementString);
	}
	formatLinks = $('#temp_container div a');
	for (var j = 0; j < formatLinks.length; j++) {
		formatLinks[j].onclick = function(){
			var tmpObject = new Object();
			availableIssues = new Object();
			tmpObject = getObjects(allIssues, 'pubDate', selectedDate);
			availableIssues = getObjects(tmpObject, 'format', this.id);
			availableIssues = availableIssues.sort(compareRepositoryNames);
			displayIssueInfoByFormat();
			return false;
		}
	}
}
function displayIssueInfoByRepository() {
	var tempBackLink = null;
	var repositoryTable = tempHead = tempBody = tempRow = tempCell = tempText = null;
	var tablePager = tempPagerLink = tempPagerSpan = null;
	var i = 0;
	$('#inner_issue_info_display').html('');
	//Create a 'Back' link to redisplay repository list
	$('#inner_issue_info_display').append('<div><a class="breadcrumb" href=""></a></div>');
	tempBackLink = $('#inner_issue_info_display div a')[0];
	tempBackLink.innerHTML = 'Back to repository list';
	tempBackLink.onclick = function(){
		displayRepositoryLinks();
		return false;
	};
	//Create paging links
	tablePager = document.createElement('div');
	tablePager.className = 'pager';
	tablePager.id = 'repository_pager';
	tempPagerLink = document.createElement('a');
	tempPagerLink.href = '#';
	tempPagerLink.className = 'prevPage';
	tempPagerLink.title = 'Previous';
	tempText = document.createTextNode('Prev');
	tempPagerLink.appendChild(tempText);
	tablePager.appendChild(tempPagerLink);
	tempPagerSpan = document.createElement('span');
	tempPagerSpan.className = 'currentPage';
	tablePager.appendChild(tempPagerSpan);
	tempText = document.createTextNode(' of ');
	tablePager.appendChild(tempText);
	tempPagerSpan = document.createElement('span');
	tempPagerSpan.className = 'totalPages';
	tablePager.appendChild(tempPagerSpan);
	tempPagerLink = document.createElement('a');
	tempPagerLink.href = '#';
	tempPagerLink.title = 'Next';
	tempText = document.createTextNode('Next');
	tempPagerLink.appendChild(tempText);
	tempPagerLink.className = 'nextPage';
	tablePager.appendChild(tempPagerLink);
	$('#inner_issue_info_display').append(tablePager);
	//Create a 2x2 table to display issue records in columnar format
	repositoryTable = document.createElement('table');
	tempHead = document.createElement('thead');
	repositoryTable.appendChild(tempHead);
	tempBody = document.createElement('tbody');
	repositoryTable.id = 'repository_table';
	//Populate table cells with individual issue records
	if (availableIssues.length == 1) {
		i = 0;
		tempRow = document.createElement('tr');
		tempCell = document.createElement('td');
		tempText = buildRepositoryIssueInfoString(i);
		tempCell.innerHTML = tempText;
		tempCell.id = i;
		tempRow.appendChild(tempCell);
		tempBody.appendChild(tempRow);
	} else if (availableIssues.length == 2) {
			i = 0;
			tempRow = document.createElement('tr');
			tempCell = document.createElement('td');
			tempText = buildRepositoryIssueInfoString(i);
			tempCell.innerHTML = tempText;
			tempRow.appendChild(tempCell);
			tempCell.id = i;
			tempCell = document.createElement('td');
			tempText = buildRepositoryIssueInfoString(i+1);
			tempCell.innerHTML = tempText;
			tempCell.id = i+1;
			tempRow.appendChild(tempCell);
			tempBody.appendChild(tempRow);
	} else if (availableIssues.length > 2) {
			for (i = 0; i < availableIssues.length; i = i + 2) {
				tempRow = document.createElement('tr');
				tempCell = document.createElement('td');
				tempText = buildRepositoryIssueInfoString(i);
				tempCell.innerHTML = tempText;
				tempCell.id = i;
				tempRow.appendChild(tempCell);
				tempCell = document.createElement('td');
				//Last cell is blank if we've run out of issue records
				if ((i+1) == availableIssues.length) {
						tempText = '';
				} else {
						tempText = buildRepositoryIssueInfoString(i+1);
				}
				tempCell.innerHTML = tempText;
				tempCell.id = i+1;
				tempRow.appendChild(tempCell);
				tempBody.appendChild(tempRow);
			}
	}
	repositoryTable.appendChild(tempBody);
	$('#inner_issue_info_display').append(repositoryTable);
	$('#repository_table').paginateTable({ rowsPerPage: 2, autoHidePager: true });
	$("#repository_table").trigger("update");
}

//function displayIssueInfoByFormat(results, textStatus) {
function displayIssueInfoByFormat() {
	var tempBackLink = null;
	var formatTable = tempHead = tempBody = tempRow = tempCell = tempText = null;
	var tablePager = tempPagerLink = tempPagerSpan = null;
	var i = 0;
	$('#inner_issue_info_display').html('');
	//Create a 'Back' link to redisplay format list
	$('#inner_issue_info_display').append('<div><a class="breadcrumb" href=""></a></div>');
	tempBackLink = $('#inner_issue_info_display div a')[0];
	tempBackLink.innerHTML = 'Back to format list';
	tempBackLink.onclick = function(){
		displayFormatLinks();
		return false;
	};
	//Create paging links
	tablePager = document.createElement('div');
	tablePager.className = 'pager';
	tablePager.id = 'format_pager';
	tempPagerLink = document.createElement('a');
	tempPagerLink.href = '#';
	tempPagerLink.className = 'prevPage';
	tempPagerLink.title = 'Previous';
	tempText = document.createTextNode('Prev');
	tempPagerLink.appendChild(tempText);
	tablePager.appendChild(tempPagerLink);
	tempPagerSpan = document.createElement('span');
	tempPagerSpan.className = 'currentPage';
	tablePager.appendChild(tempPagerSpan);
	tempText = document.createTextNode(' of ');
	tablePager.appendChild(tempText);
	tempPagerSpan = document.createElement('span');
	tempPagerSpan.className = 'totalPages';
	tablePager.appendChild(tempPagerSpan);
	tempPagerLink = document.createElement('a');
	tempPagerLink.href = '#';
	tempPagerLink.title = 'Next';
	tempText = document.createTextNode('Next');
	tempPagerLink.appendChild(tempText);
	tempPagerLink.className = 'nextPage';
	tablePager.appendChild(tempPagerLink);
	$('#inner_issue_info_display').append(tablePager);
	//Create a 2x2 table to display issue records in columnar format
	formatTable = document.createElement('table');
	tempHead = document.createElement('thead');
	formatTable.appendChild(tempHead);
	tempBody = document.createElement('tbody');
	formatTable.id = 'format_table';
	//Populate table cells with individual issue records
	if (availableIssues.length == 1) {
		i = 0;
		tempRow = document.createElement('tr');
		tempCell = document.createElement('td');
		tempText = buildFormatIssueInfoString(i);
		tempCell.innerHTML = tempText;
		tempCell.id = i;
		tempRow.appendChild(tempCell);
		tempBody.appendChild(tempRow);
	} else if (availableIssues.length == 2) {
			i = 0;
			tempRow = document.createElement('tr');
			tempCell = document.createElement('td');
			tempText = buildFormatIssueInfoString(i);
			tempCell.innerHTML = tempText;
			tempRow.appendChild(tempCell);
			tempCell.id = i;
			tempCell = document.createElement('td');
			tempText = buildFormatIssueInfoString(i+1);
			tempCell.innerHTML = tempText;
			tempCell.id = i+1;
			tempRow.appendChild(tempCell);
			tempBody.appendChild(tempRow);
	} else if (availableIssues.length > 2) {
			for (i = 0; i < availableIssues.length; i = i + 2) {
				tempRow = document.createElement('tr');
				tempCell = document.createElement('td');
				tempText = buildFormatIssueInfoString(i);
				tempCell.innerHTML = tempText;
				tempCell.id = i;
				tempRow.appendChild(tempCell);
				tempCell = document.createElement('td');
				//Last cell is blank if we've run out of issue records
				if ((i+1) == availableIssues.length) {
						tempText = '';
				} else {
						tempText = buildFormatIssueInfoString(i+1);
				}
				tempCell.innerHTML = tempText;
				tempCell.id = i+1;
				tempRow.appendChild(tempCell);
				tempBody.appendChild(tempRow);
			}
	}
	formatTable.appendChild(tempBody);
	$('#inner_issue_info_display').append(formatTable);
	$('#format_table').paginateTable({ rowsPerPage: 2, autoHidePager: true });
	$("#format_table").trigger("update");
}
function buildRepositoryIssueInfoString(issueIndex) {
	var tempIssueId = tempPubId = tempPubDate = tempRepositoryId = tempPhysCondition = tempFormat = tempArchiveStatus = tempProvenance = tempNotes = tempUpdateDate = null;
	//Build a string to display issue info for selected day and format
	issueInfoDisplayString = '';
	tempIssueId = availableIssues[issueIndex].issueId;
	tempPubId = availableIssues[issueIndex].pubId;
	tempPubDate = availableIssues[issueIndex].pubDate;
	tempRepositoryId = availableIssues[issueIndex].repositoryId;
	tempRepositoryName = availableIssues[issueIndex].repositoryName;
	tempPhysCondition = availableIssues[issueIndex].physCondition;
	if (tempPhysCondition == 'cccc' || tempPhysCondition == null)
		tempPhysCondition = 'Unknown';
	tempFormat = availableIssues[issueIndex].format;
	if (tempFormat == "format unspecified/unknown") {
		tempFormat = "Unspecified or unknown";
	} else if (tempFormat == "Digital pdf") {
		tempFormat = "Digital (pdf)";
	}
	tempArchiveStatus = availableIssues[issueIndex].archiveStatus;
	/*
	//Per Andy, suppress provenance until there is meaningful field data
	tempProvenance = availableIssues[issueIndex].provenance;
	if (tempProvenance == 'pppp' || tempProvenance == null || tempProvenance == '')
		tempProvenance = 'Unknown';
	*/
	tempUpdateDate = availableIssues[issueIndex].updateDate;
	tempNotes = availableIssues[issueIndex].notes;
	issueInfoDisplayString +=   '<br /><span class="issue_info_label">ISSUE DATE: &nbsp;</span>' + selectedDateFormatted + '<br />' +
								'<span class="issue_info_label">REPOSITORY: &nbsp;</span>' + tempRepositoryName + '<br />';							
	if (tempPhysCondition == "condition unspecified/unknown") {
		issueInfoDisplayString += '<span class="issue_info_label">CONDITION: &nbsp;</span>Unspecified or unknown<br />';
	} else {
		issueInfoDisplayString += '<span class="issue_info_label">CONDITION: &nbsp;</span>' + tempPhysCondition + '<br />';
	}
	issueInfoDisplayString += '<span class="issue_info_label">FORMAT: &nbsp;</span>' + tempFormat + '<br />';
	if (tempArchiveStatus == "archive status unspecified/unknown") {
		issueInfoDisplayString += '<span class="issue_info_label">ARCHIVE STATUS: &nbsp;</span>Unspecified or unknown<br />';
	} else {
		issueInfoDisplayString += '<span class="issue_info_label">ARCHIVE STATUS: &nbsp;</span>' + tempArchiveStatus + '<br />';
	}
	if (tempNotes != '' && tempNotes != null) {
		issueInfoDisplayString +=	'<span class="issue_info_label">NOTES: &nbsp;</span>' + tempNotes + '<br />';
	}
	if (tempUpdateDate != '0000-00-00' && tempUpdateDate != null) {
		tempUpdateDate = toTitleCase(monthAbbrevArray[parseInt(tempUpdateDate.substr(5,2),10)-1])+ " " + parseInt((tempUpdateDate.substr(8,2)),10) + ", " + tempUpdateDate.substr(0,4);
		issueInfoDisplayString +=	'<span class="issue_info_label">LAST UPDATED: &nbsp;</span>' + tempUpdateDate + '<br />';
	}
	issueInfoDisplayString = issueInfoDisplayString + '<br />';
	return issueInfoDisplayString;
}
function buildFormatIssueInfoString(issueIndex) {
	var tempIssueId = tempPubId = tempPubDate = tempRepositoryId = tempPhysCondition = tempFormat = tempArchiveStatus = tempProvenance = tempNotes = tempUpdateDate = null;
	//Build a string to display issue info for selected day and format
	issueInfoDisplayString = '';
	tempIssueId = availableIssues[issueIndex].issueId;
	tempPubId = availableIssues[issueIndex].pubId;
	tempPubDate = availableIssues[issueIndex].pubDate;
	tempRepositoryId = availableIssues[issueIndex].repositoryId;
	tempRepositoryName = availableIssues[issueIndex].repositoryName;
	tempPhysCondition = availableIssues[issueIndex].physCondition;
	if (tempPhysCondition == 'cccc' || tempPhysCondition == null)
		tempPhysCondition = 'Unknown';
	tempFormat = availableIssues[issueIndex].format;
	if (tempFormat == "format unspecified/unknown") {
		tempFormat = "Unspecified or unknown";
	} else if (tempFormat == "Digital pdf") {
		tempFormat = "Digital (pdf)";
	}
	tempArchiveStatus = availableIssues[issueIndex].archiveStatus;
	/*
	//Per Andy, suppress provenance until there is meaningful field data
	tempProvenance = availableIssues[issueIndex].provenance;
	if (tempProvenance == 'pppp' || tempProvenance == null || tempProvenance == '')
		tempProvenance = 'Unknown';
	*/
	tempUpdateDate = availableIssues[issueIndex].updateDate;
	tempNotes = availableIssues[issueIndex].notes;
	issueInfoDisplayString +=   '<br /><span class="issue_info_label">ISSUE DATE: &nbsp;</span>' + selectedDateFormatted + '<br />' +
								'<span class="issue_info_label">REPOSITORY: &nbsp;</span><a href="" onclick="displayRepositoryInfoFromFormat(' + issueIndex + '); return false;">' + tempRepositoryName + '</a><br />';
	if (tempPhysCondition == "condition unspecified/unknown") {
		issueInfoDisplayString += '<span class="issue_info_label">CONDITION: &nbsp;</span>Unspecified or unknown<br />';
	} else {
		issueInfoDisplayString += '<span class="issue_info_label">CONDITION: &nbsp;</span>' + tempPhysCondition + '<br />';
	}
	issueInfoDisplayString += '<span class="issue_info_label">FORMAT: &nbsp;</span>' + tempFormat + '<br />';
	if (tempArchiveStatus == "archive status unspecified/unknown") {
		issueInfoDisplayString += '<span class="issue_info_label">ARCHIVE STATUS: &nbsp;</span>Unspecified or unknown<br />';
	} else {
		issueInfoDisplayString += '<span class="issue_info_label">ARCHIVE STATUS: &nbsp;</span>' + tempArchiveStatus + '<br />';
	}
	if (tempNotes != '' && tempNotes != null) {
		issueInfoDisplayString +=	'<span class="issue_info_label">NOTES: &nbsp;</span>' + tempNotes + '<br />';
	}
	if (tempUpdateDate != '0000-00-00' && tempUpdateDate != null) {
		tempUpdateDate = toTitleCase(monthAbbrevArray[parseInt(tempUpdateDate.substr(5,2),10)-1])+ " " + parseInt((tempUpdateDate.substr(8,2)),10) + ", " + tempUpdateDate.substr(0,4);
		issueInfoDisplayString +=	'<span class="issue_info_label">LAST UPDATED: &nbsp;</span>' + tempUpdateDate + '<br />';
	}
	issueInfoDisplayString = issueInfoDisplayString + '<br />';
	return issueInfoDisplayString;
}
function displayRepositoryInfo(results, textStatus) {
	var tempReposName = tempReposType = tempReposId = tempStreet1 = tempStreet2 = tempReposCity = tempReposState = tempPostalCode = tempLastUpdated = null;
	var tempReposNote = tempHomePage = tempOpac = null;
	reposInfoDisplayString = '';
	var reposAddressString = '';
	if ((results.search(/Error/i) != -1) || (results.search(/\<b>Notice/i) != -1 )) {
		document.writeln(results);
	} else {
		clearRepositoryInfo();
		var data = JSON.parse(results);
		tempReposName = data.repositoryName;
		tempReposType = data.repositoryTypeName;
		if (data.street1 != null) {
			tempStreet1 = toTitleCase(data.street1.toLowerCase());
		}
		if (data.street2 != null) {
			tempStreet2 = toTitleCase(data.street2.toLowerCase());
		}
		tempReposCity = toTitleCase(data.city.toLowerCase());
		tempReposState = data.countryId;
		tempReposState = data.countryId.substr(0,2).toUpperCase();
		tempPostalCode = data.postalCode;
		tempReposId = data.repositoryId;
		tempMarcOrgCode = data.marcOrgCode;
		tempOCLCId = data.OCLCId;
		tempLastUpdated = data.reposUpdateDate;
		if (data.repositoryNote != null) {
			tempReposNote = data.repositoryNote;
		}
		if (data.homeURI != null) {
			tempHomePage = data.homeURI;
		}
		if (data.opacURI != null) {
			tempOpac = data.opacURI;
		}
		//Build repository address display string
		if (tempStreet2 != '') {
			reposAddressString += tempStreet1 + '<br />' + tempStreet2 + '<br />';
		} else if (tempStreet1 != '') {
			reposAddressString += tempStreet1 + '<br />';
		}
		reposAddressString += tempReposCity + ', ' + tempReposState;
		if (tempPostalCode != null) {
			reposAddressString += ' ' + tempPostalCode + '<br />';
		} else {
			reposAddressString += '<br />';
		}
		//Build the rest of repository display string
		if (tempHomePage != null && tempHomePage != '') {
			reposInfoDisplayString = '<a href="' + tempHomePage + '" target="_blank">(' + tempReposId + ') ' + tempReposName + '</a><br />';
		} else if (tempOpac != null && tempOpac != '') {
			reposInfoDisplayString = '<a href="' + tempOpac + '" target="_blank">(' + tempReposId + ') ' + tempReposName + '</a><br />';
		} else {
			reposInfoDisplayString = '(' + tempReposId + ') ' + tempReposName + '<br />'
		}
		reposInfoDisplayString += reposAddressString;
		if (tempReposNote != null && tempReposNote != '') {
			reposInfoDisplayString += '<div class="repos_note">' + tempReposNote + '</div>';
		}
		$('<h4>Repository Information</h4><div class="block" id="repository_info"><p>' + reposInfoDisplayString + '</p></div>').insertAfter('#title_info');
	}
	return false;
}
function displayRepositoryInfoFromFormat(tId) {
	$.get("get_repository_info.php", { 'selectedRepositoryId': availableIssues[tId].repositoryId }, displayRepositoryInfo);
}
function whiteOutCalendar() {
	//Simulates disabled state
	//For accessibility, will need to assign 'disabled' classes
	$('span.ui-state-default').css('backgroundColor', '#FFFFFF').css('color', '#FFFFFF');
	$('a.ui-state-default').css('backgroundColor', '#FFFFFF').css('color', '#FFFFFF');
	$('td.publication_date').css('backgroundColor', '#FFFFFF');
	$('td.selected_publication_date').css('backgroundColor', '#FFFFFF');
	$('td.selected_publication_date a').css('backgroundColor', '#FFFFFF');
	$('th').css('backgroundColor', '#FFFFFF').css('color', '#FFFFFF');
	$('.ui-datepicker-title').css('backgroundColor', '#FFFFFF').css('color', '#FFFFFF');
}
function clearAvailableMonths() {
	$('.month_box').attr('class', 'month_box month_box_not_available');
}
function clearRepositoryInfo() {
	$('h4:contains("Repository Information")').remove();
	if ($('#repository_info').length != 0) {
		$('#repository_info').remove();
	}
}
function previous(){ 
  new_page = parseInt($('#current_page').val()) - 1;  
  //Run this function if there are any pagination links before the current active one  
  if($('.active_page').prev('.page_link').length==true){  
      go_to_page(new_page);  
  }
}
function next(){
  new_page = parseInt($('#current_page').val()) + 1;
  //Run this function if there are any pagination links after the current active one  
  if($('.active_page').next('.page_link').length==true){ 
      go_to_page(new_page);  
  }
}
function go_to_page(page_num){
  //Get number of items to show per page  
  show_per_page = parseInt($('#show_per_page').val());  
  //Get element number to start slice from  
  start_from = page_num * show_per_page;  
  //Get element number to end slice at
  end_on = start_from + show_per_page;  
  //Hide all child elements of temp_container div, then show only links in the pagination slice
  $('#temp_container').children().css('display', 'none').slice(start_from, end_on).css('display', 'block');  
  //Get the pagination link that has longdesc attribute of the current page and add active_page class to it.
  //Then remove that class from previously active page link
  $('.page_link[longdesc=' + page_num +']').addClass('active_page').siblings('.active_page').removeClass('active_page');  
  if(page_num == 0) {
  	//$('.previous_link').css('visibility','hidden');
  	$('.previous_link').css('color','#303030').css('textDecoration', 'none');
  } else {
  	//$('.previous_link').css('visibility','visible');
  	$('.previous_link').css('color','#00224C').css('textDecoration', 'underline');
  }
	if(page_num == number_of_pages - 1) {
  	//$('.next_link').css('visibility','hidden');
  	$('.next_link').css('color','#303030').css('textDecoration', 'none');
  } else {
  	//$('.next_link').css('visibility','visible');
  	$('.next_link').css('color','#00224C').css('textDecoration', 'underline');
  }  
  //Update current page input field  
  $('#current_page').val(page_num);  
}
function getMonthNumber(str) {
	for (var m in tempAvailableMonthsObject) {
		if (tempAvailableMonthsObject[m] == str)
			return parseInt(m,10);
	}
}
function addOption(selectbox,text,value) {
	var optn = document.createElement("option");
	optn.text = text;
	optn.value = value;
	selectbox.options.add(optn);
}
function padDate(num) {
	return (num < 10 ? '0' : '') + num;
}
function hasClass(ele,cls) {
	return ele.className.match(new RegExp('(\\s|^)'+cls+'(\\s|$)'));
}
function addClass(ele,cls) {
	if (!this.hasClass(ele,cls)) ele.className += " "+cls;
}
function getObjects(obj, key, val) {
	var objects = [];
	for (var i in obj) {
		if (!obj.hasOwnProperty(i)) continue;
			if (typeof obj[i] == 'object') {
				objects = objects.concat(getObjects(obj[i], key, val));
			} else if (i == key && obj[key].search(val) != -1) {
				objects.push(obj);
		}
	}
	return objects;
}
function compareRepositoryIds(a,b) {
	if (a.repositoryId>b.repositoryId) {
		return 1;
	} else if (b.repositoryId>a.repositoryId) {
		return -1;
	} else if (a.repositoryId==b.repositoryId) {
		return 0;
	}
}
function compareRepositoryNames(a,b) {
	if (a.repositoryName>b.repositoryName) {
		return 1;
	} else if (b.repositoryName>a.repositoryName) {
		return -1;
	} else if (a.repositoryName==b.repositoryName) {
		return 0;
	}
}
function compareFormats(a,b) {
	if (a.format>b.format) {
		return 1;
	} else if (b.format>a.format) {
		return -1;
	} else if (a.format==b.format) {
		return 0;
	}
}
function toTitleCase(str)
{
    return str.replace(/\w\S*/g, function(txt){return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();});
}